### ISSUE TITLE
Ambiguous legal moves

### ISSUE THREAD

**Issue by check-side** [AdmiralAdama99/PHPChess#5]
When importing the FEN 'r1bqkb1r/ppp2ppp/2n2n2/3pp3/4P3/3P1N2/PPP1BPPP/RNBQK2R w KQkq d6 0 5' the script lists several legal moves. One of them is 'Nd2', but that's ambiguous. It should be clarified to 'Nbd2' and 'Nfd2'.

**Comment by RedDragonWebDesign** [comment]
Thanks for submitting.

Notes to self:
- Good test FEN: `K2k4/8/8/8/8/5N2/8/1N6 w - d6 0 5`
- Error is not necessarily in disambiguation part of the code, i.e. `ChessRulebook::clarify_ambiguous_pieces()`. Move list is already short a move by the time that code is reached.
- `K2k4/8/8/8/8/5N2/8/5N2 w - d6 0 5` and `K2k4/8/8/8/8/8/8/1N3N2 w - d6 0 5` work correctly.
